name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write

    outputs:      
      published: ${{ steps.release.outputs.published }}
      published_version: ${{ steps.release.outputs.published_version }}
      published_version_major: ${{ steps.release.outputs.published_version_major }}
      published_version_minor: ${{ steps.release.outputs.published_version_minor }}
      published_version_patch: ${{ steps.release.outputs.published_version_patch }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      id: release
      uses: tumaysem/python-semantic-release@master
      with:
        additional_options: --github
        github_token: ${{ secrets.GITHUB_TOKEN }}

  print-output:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Print Published Value
      run: |
        echo "Published Value: ${{ steps.release.outputs.published }}"
        echo "Published Version: ${{ steps.release.outputs.published_version }}"
        echo "Published Version MAJOR: ${{ steps.release.outputs.published_version_major }}"
        echo "Published Version MINOR: ${{ steps.release.outputs.published_version_minor }}"
        echo "Published Version PATCH: ${{ steps.release.outputs.published_version_patch }}"

  container_build:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.published == 'True'
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: autoagora-processor
        tags: >
          latest
          v${{ needs.release.outputs.published_version_major }}
          v${{ needs.release.outputs.published_version_major }}.${{ needs.release.outputs.published_version_minor }}
          v${{ needs.release.outputs.published_version}}
        containerfiles: |
          ./Dockerfile
    - name: Push
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/semiotic-ai
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"
